import type { Metadata } from 'next'
import './global.css'
import Nav from '@/components/Nav'

export const metadata: Metadata = {
  title: 'Tong Zhou | Site',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <main className="max-w-[960px] mx-auto">
          <Nav />
          {children}
        </main>
      </body>
    </html>
  )
}
