import type { Metadata } from 'next'
import './global.css'
import Link from 'next/link'
import { primaryColor } from '@/utils/consts'

export const metadata: Metadata = {
  title: 'Tong Zhou | Site',
  // description: 'Generated by create next app',
}

const linkList = [
  { href: '/', label: 'Home' },
  { href: '/about', label: 'About' },
]

function Logo() {
  return (
    <div className="inline-flex justify-center items-center font-bold text-[17px] cursor-pointer">
      <span>Tong</span>
      <span className="inline-flex items-center justify-center w-[44px] h-[44px] text-white rounded-[7px] ml-[7px]" style={{ backgroundColor: primaryColor }}>
        Zhou
      </span>
    </div>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <main className="max-w-[960px] mx-auto">
          <nav className="flex justify-between items-center p-4">
            <div className="w-[100px]">
              <Logo />
            </div>
            <div className="flex-1 flex justify-center">
              <div className="md:block flex">
                {linkList.map((link) => (
                  <Link key={link.href} href={link.href} className="inline-block w-[100px]">
                    {link.label}
                  </Link>
                ))}
              </div>
            </div>
            <div className="w-[100px]"></div>
            <div className="md:hidden">啦啦</div>
          </nav>
          {children}
        </main>
      </body>
    </html>
  )
}
